### ISSUE TITLE
Login button doesn't show up with basic example

### ISSUE THREAD

**Issue by laurensV** [EOSIO/ual-lynx#28]
When trying out the basic example from the https://github.com/EOSIO/ual-plainjs-renderer repo, it doesn't show the lynx login button, only the scatter button:

```
import { UALJs } from 'ual-plainjs-renderer'
import { Scatter } from 'ual-scatter'
import { Lynx } from 'ual-lynx'

const myCallback = arrayOfUsers => {
  // Execute on successful user authentication
}

const myChain = {
  chainId: MY_CHAIN_ID,
  rpcEndpoints: [{
    protocol: MY_CHAIN_PROTOCOL,
    host: MY_CHAIN_HOST,
    port: MY_CHAIN_PORT,
  }]
}

const myAppName = 'My UAL App'

const scatter = new Scatter([myChain], { appName: myAppName })
const lynx = new Lynx([myChain], { appName: myAppName })

const myAppRoot = {
  containerElement: document.getElementById('my-ual-app')
}

const ual = new UALJs(myCallback, [myChain], myAppName, [scatter, lynx], myAppRoot)

ual.init()
```

Not sure if this issue is caused by `ual-lynx` or by `ual-plainjs-renderer`..

**Comment by jeffreyssmith2nd** [comment]
Are you loading the example in the Lynx browser?

Buttons will only show up in an environment that they support. So Lynx for example, Dapps only work with Lynx in the embedded browser that is part of the app.

In addition, if an Authenticator is the only one supported in the given environment it will attempt to autologin. So in Lynx you actually should never see the button, you should be auto logged in with your active Lynx account.

**Comment by laurensV** [comment]
Thanks for the quick reply, makes total sense!

**Comment by laurensV** [comment]
I still cannot get ual-lynx to automatically sign me in when I am in the Lynx app. It just shows me the page without the login button, but the loginCallback function is never called. The other mobile wallet integrations (ual-meetone and ual-token-pocket) are working fine and they do automatically log me in. Unfortunately this does not work for ual-lynx and it is also hard to debug what is going wrong as I can only test it within the Lynx app. Any ideas of the best way to debug this?

**Comment by ismyhc** [comment]
I suggest this library if you need to debug with console.

https://github.com/Tencent/vConsole

**Comment by chris-allnutt** [comment]
@laurensV According to #30 this shouldn't be a problem with the latest lynx as of May 12th.  Can you test and verify?

**Comment by chris-allnutt** [comment]
Closing for now, please open an new issue if this still persists
