### ISSUE TITLE
Add support for multiple chains since Lynx supports more than main net

### ISSUE THREAD

**Issue by ismyhc** [EOSIO/ual-lynx#41]
I see that right now ual-lynx is hardcoded to main net. We now support multiple chains. You can obtain the chainId for the selected account in lynx be calling:

```
requestSetAccount
```

It will return an object which has a chainId property at the root.

```
{
"account": Object,
"chainId": String,
...
```

Right now iOS and Android support: Desktop will support these in a few weeks.
4667b205c6838ef70ff7988f6e8257e8be0e1284a2f59699054a018f743b1d11
aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906
d5a3d18fbb3c084e3b1f3fa98c21014b5f3db536cc15d08f9f6479517c6a3d86

In a couple of days iOS and Android will support WAX as well. Desktop will support WAX in a few weeks.
1064487b3cd1a897ce03ae5b6a865651747e2e152090f99c1d19d44e01aea5a4

Support is on the horizon for Jungle Testnet and of course Lynx Chain Testnet

docs: https://developers.eoslynx.com/sdk

**Comment by jlamarr22** [comment]
After updates to `ual-lynx`, this package supports any chainId that you send to it.
