### ISSUE TITLE
Add Android and Desktop 2.0 sdk function support parity

### ISSUE THREAD

**Issue by ismyhc** [EOSIO/ual-lynx#42]
```
requestArbitrarySignature 
```

I see that in the ual-lynx lib that its only supporting iOS. As of today Android supports all lynxMobile SDK functions.

On that same note we have Lynx Desktop 2.0 in private beta at the moment. The good news is that Lynx Desktop 2.0 also uses the exact same SDK. It supports most functions that are not mobile specific. One thing to note is that Desktop 2.0 has a different user agent.

There are updated docs that document our platforms support for each SDK function.

https://developers.eoslynx.com/sdk

**Comment by ismyhc** [comment]
Im gonna start on this today. :)

**Comment by ismyhc** [comment]
@jeffreyssmith2nd any update on this merge? We have a couple of third party dapps waiting on this :).

Thanks!

**Comment by jeffreyssmith2nd** [comment]
@ismyhc This has been merged, thanks for the contribution!
